-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggJZa9pik7otdXDRG
FIBl+0tMuHILOE5epPR1mvpLmi6gCgYIKoZIzj0DAQehRANCAAT5d9oIgJWKWy4q
XAj/CS/m/RH/QPApW3D2Wy4D/Yzn1/EGgrAhMaNRbQ62gNqh+FY2RBpFBJIUOyAW
oIh+QLRX
-----END PRIVATE KEY-----